name: lobe-chat-development
services:
  postgresql:
    image: pgvector/pgvector:pg17
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME:-lobechat}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}'
    env_file:
      - ../../.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: lobe-minio
    ports:
      - '${MINIO_PORT:-9000}:${MINIO_PORT:-9000}'
      - '9001:9001'
    networks:
      - lobe-network
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_API_CORS_ALLOW_ORIGIN=*'
    env_file:
      - ../../.env
    restart: always
    entrypoint: >
      /bin/sh -c "
        minio server /etc/minio/data --address ':${MINIO_PORT:-9000}' --console-address ':9001' &
        MINIO_PID=$$!
        while ! curl -s http://localhost:${MINIO_PORT:-9000}/minio/health/live; do
          echo 'Waiting for MinIO to start...'
          sleep 1
        done
        sleep 5
        mc alias set myminio http://localhost:${MINIO_PORT:-9000} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        echo 'Creating bucket ${MINIO_LOBE_BUCKET:-lobe}'
        mc mb myminio/${MINIO_LOBE_BUCKET:-lobe}
        wait $$MINIO_PID
      "

  searxng:
    image: searxng/searxng
    container_name: lobe-searxng
    ports:
      - '8080:8080'
    volumes:
      - './searxng-settings.yml:/etc/searxng/settings.yml'
    environment:
      - 'SEARXNG_SETTINGS_FILE=/etc/searxng/settings.yml'
    restart: always
    networks:
      - lobe-network
    env_file:
      - ../../.env

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
